### ISSUE TITLE
renaming the top-level conda environment

### ISSUE THREAD

**Issue by rvosa** [o-william-white/skim2mito#28]
The top-level conda env in workflow/envs/conda_env.yaml is now referred to as 'snakemake', although it is a bit richer than just snakemake. To avoid name clashes in host systems, perhaps this can be renamed to skim2mt

**Comment by o-william-white** [comment]
This shouldn't be a problem... @bwprice has suggested renaming the tool to skim2mito? How do we feel about another name change?

**Comment by bwprice** [comment]
+1 million on a name change to skim2mito - much easier to say :)

**Comment by rvosa** [comment]
I don't care what it's called as long as it's reasonably unique. In the end, the conda environment is just going to be a folder on a computer and that folder can't be called 'snakemake' because there could easily be one by that name already there. 'skim2mito' is fine for that.

**Comment by o-william-white** [comment]
Name of tool and top level conda environment updated to skim2mito

**Comment by bwprice** [comment]
[heart]         Ben Price reacted to your message:
________________________________
